// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2-C2OZnsfFUKQTj94bv9RDBUkCTxghSk',
    appId: '1:67697637109:web:43e23b478e57953d5037bc',
    messagingSenderId: '67697637109',
    projectId: 'social-media-app-61191',
    authDomain: 'social-media-app-61191.firebaseapp.com',
    storageBucket: 'social-media-app-61191.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWFkBMuqOg8rTEs6EWmhiyMa4jHWZbvYg',
    appId: '1:67697637109:android:d19e7fe779302a625037bc',
    messagingSenderId: '67697637109',
    projectId: 'social-media-app-61191',
    storageBucket: 'social-media-app-61191.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3sZv3HJCUjLn_rzwXhdygwGSEBpFwzVA',
    appId: '1:67697637109:ios:35b9c52d92e4c7ed5037bc',
    messagingSenderId: '67697637109',
    projectId: 'social-media-app-61191',
    storageBucket: 'social-media-app-61191.appspot.com',
    iosClientId: '67697637109-c884abu15ofc84rbvi9fgsknnv23bnhf.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3sZv3HJCUjLn_rzwXhdygwGSEBpFwzVA',
    appId: '1:67697637109:ios:35b9c52d92e4c7ed5037bc',
    messagingSenderId: '67697637109',
    projectId: 'social-media-app-61191',
    storageBucket: 'social-media-app-61191.appspot.com',
    iosClientId: '67697637109-c884abu15ofc84rbvi9fgsknnv23bnhf.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMediaApp',
  );
}
